# name: Deploy to Vercel

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Login to Docker Hub
#         run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

#       - name: Build and push Docker image
#         run: |
#           docker build -t <your-docker-username>/<your-image-name> .
#           docker push <your-docker-username>/<your-image-name>
